""""""""
" Front matter

" Store config files in ~/cfg.
" See http://tlvince.com/vim-respect-xdg.
set runtimepath^=$XDG_CONFIG_HOME/vim runtimepath+=$XDG_CONFIG_HOME/vim/after
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo

" I like to run fish but vim needs a POSIX-compatible shell.
set shell=/bin/bash

""""""""
" Pathogen

call pathogen#infect()

""""""""
" Options

" Start with some decent defaults.
set nocompatible

" Read modelines.
" (Gentoo disables this by default.)
set modeline

" Enable syntax highlighting.
syntax on

" Hard tabs are displayed as 8 spaces.
set tabstop=8

" Tab key inserts spaces.
set expandtab

" Tab key inserts 4 spaces.
"set softtabstop=4

" Shifting indents 4 spaces.
set shiftwidth=4

" Shifting aligns to a multiple of shiftwidth.
set shiftround

" Tab key at the beginning of a line inserts shiftwidth spaces.
set smarttab

" Always show the status line.
set laststatus=2

" Show a line at the 80-character mark
set colorcolumn=80

" Make tabs and non-breaking spaces visible.
" Tabs will appear as »‐‐‐‐‐‐‐.
" Non-breaking spaces will appear as a middle dot.
set list listchars=tab:»‐,nbsp:·

" Options for automatic formatting.
" tc: wrap text and comments at textwidth
" l: don't break lines that are already past textwidth
" r: enter key inside comment inserts comment character
" j: remove comment character when joining lines
" q: let gq format comments
set formatoptions=tcrqlj

" Insert one space after a period when joining lines.
set nojoinspaces

" Recognize C-style and Python-style line comments, and bulleted lists.
" Don't recognize multi-line C comments.
set comments=://,b:#,fb:-

" Nobody uses octal.
set nrformats-=octal

" Disable C indenting. Should be disabled by nocompatible.
set nocindent

" Copy indent from previous line.
set autoindent

" Search while typing.
set incsearch

" Highlight matches.
set hlsearch

" Don't write backup~ files.  I have real backups.
set nobackup

" But keep a copy during writes.
set writebackup

" Save undo history.
set undofile

" Titles
set title
set titleold=

" Easy toggle for paste mode
set pastetoggle=<F2>

""""""""
" Mappings

" Make navigating tabs easier.
" ^P and ^N scroll through tabs.
map <C-p> :tabprev<cr>
map <C-n> :tabnext<cr>

" Make Y yank to the end of the line,
" for consistency with C and D.
map Y y$

" Make :W an alias for :w.
" Common typo.
command W write

let g:ctrlp_map = '<C-t>'

""""""""
" Filetypes

" Disable filetype plugin and filetype indent.
filetype plugin off
filetype indent off

" But enable filetype detection.
filetype on

" Add some new filetypes.
" And override some dumb default filetypes.
autocmd filetypedetect BufNewFile,BufRead *.ll setlocal filetype=llvm
autocmd filetypedetect BufNewFile,BufRead *.mako setlocal filetype=mako
autocmd filetypedetect BufNewFile,BufRead *.md setlocal filetype=markdown

" Enable go plugins.
" Use goimports.
autocmd filetype go filetype plugin on
let g:gofmt_command = "goimports"

" Enable :Man
runtime ftplugin/man.vim

" Disable modelines in git commit messages.
" Limit width to 72 charaters.
autocmd BufRead COMMIT_EDITMSG setlocal nomodeline textwidth=72

" Use hard tabs in C-based languages.
autocmd filetype c setlocal noexpandtab shiftwidth=8
autocmd filetype cpp setlocal noexpandtab shiftwidth=8
autocmd filetype go setlocal noexpandtab shiftwidth=8
autocmd filetype javascript setlocal noexpandtab shiftwidth=8

""""""""
" Colors

highlight link pythonImport Keyword
highlight link pythonFunction Normal
highlight link pythonDecorator Normal
highlight link pythonDottedName Normal

" In HTML, don't stylize the contents of <em> and <a> and the like.
let g:html_no_rendering = 1
