export EDITOR=vim
export PAGER=less
export GOPATH=$HOME/go
export XDG_CONFIG_HOME=$HOME/cfg
export XDG_CACHE_HOME=$HOME/var/cache
export XDG_DATA_HOME=$HOME/var

export DVDCSS_CACHE=$XDG_CACHE_HOME/dvdcss
export LESSHISTFILE=$XDG_DATA_HOME/less/history
export GNUPGHOME=$XDG_CONFIG_HOME/gnupg
export VIMINIT='let $MYVIMRC="$HOME/cfg/vim/vimrc" | source $MYVIMRC'
export PSQLRC=$XDG_CONFIG_HOME/psql/psqlrc
export XINITRC=$XDG_CONFIG_HOME/X11/xinitrc
